# config for training multi-channel conformer model
trainer:
  optimizer: "adam"
  lr: 1.0e-3
  min_lr: 1.0e-6
  decay: 1.0e-2
  weight_decay: 1.0e-5
  warmup: 10000
  grad_thresh: 5.0

objective:
  objective_type: "huber"
  reduction: "sum"

model:
  num_spk: 2
  num_noise: 1
  model_type: "blstm"
  hidden_dim: 1024
  num_layers: 4
  dropout_rate: 0.1

feature:
  frame_length: 512
  frame_shift: 256
  ipd: 1,0;2,0;3,0;4,0;5,0;6,0
  idim: 1799
  num_bins: 257

data:
  feature: "precomputed"
  train_dir: "data/train"
  valid_dir: "data/valid"
  sample_rate: 16000

dataloader:
  shuffle: true
  batch_size: 32  # batch size per GPU
  num_workers: 4
  drop_last: false

tensorboard:
  log_dir: "tb_logs"
  log_interval: 1000  # Set to -1 to disable printing STFTs
  num_samples: 4
